### PR TITLE
Crude fix for the "exit 7" problem.

### LINKED ISSUE #54: `mimeopen` uses wrong exit code even if execution went correctly
For some reason, this `exit 7` is executed even if execution went correctly:

https://github.com/mbeijen/File-MimeInfo/blob/cd55818f754a74e921db2e37b951b59b4916b408/mimeopen#L185

Removing the offending line results in correct execution and the correct error code (0).

This is a problem since `xdg-open`, if it doesn't detect a known desktop environment, uses `mimeopen` if it's available, and checks its exit code. If it's nonzero, execution continues as if `mimeopen` failed, resulting in `xdg-open` opening the file multiple times.

This is described in more detail on [Gentoo Forums](https://forums.gentoo.org/viewtopic-p-8792910.html?sid=782b75ad0f840a9bd225f32261a55880), albeit nobody pointed out it was an issue with `mimeopen`.

### PR DESCRIPTION
**Pull request by slatian**
Should fix #54.

### CODE REVIEW

**Comment by slatian** [comment]
Whatever `.pre-commit-config.yaml` is supposed to do …

**Comment by mbeijen** [comment]
Thanks for your fix! I was halfway setting up the .pre-commit config apparently :-)

**Comment by slatian** [comment]
Thanks for accepting that so fast! I hope distributions will ship it soon.

**Comment by mbeijen** [comment]
It depends on your distro, typically fedora and Debian testing are pretty fast. Please note I still need to create a release. I will do so in the next days

**Pull request merged**
